import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "MoneyTrack",
  description: "Generated by spwtt.d",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${notoSansThai.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex flex-col lg:flex-row">
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
